// Keith Hough, keithsportfolio.com, 2017

var beerIpsum = [
    'Alewerks "Paycheck Porter".',
    'Alewerks "Weekend Lager".',
    'Big Sky "Moose Drool" Brown Ale.',
    'Big Sky "Trout Slayer" Wheat Ale.',
    'Breckenridge "Oatmeal Stout".',
    'Breckenridge "Avalanche" Amber Ale.',
    'Bristol "Laughing Lab" Scottish Ale.',
    'Bristol "Red Rocket" Pale Ale.',
    'Capital City "Pale Rider Ale".',
    'Capital City "Prohibition Porter".',
    'Copper Canyon "Buffalo Jump" Stout.',
    'Copper Canyon "Devil\'s Peak" IPA.',
    'Deschutes "Obsidian Stout".',
    'Deschutes "American Wheat".',
    'Epic "Intermountain Wheat".',
    'Epic "Blue Ski" Lager.',
    'Fat Bottom "Knockout" IPA.',
    'Fat Bottom "Ruby" American Red Ale.',
    'Flying Fish "Hopfish" IPA.',
    'Flying Fish "Double IPA".',
    'Georgetown "9LB Porter".',
    'Georgetown "Bodhizafa" IPA.',
    'Grizzly Peak "Bear Paw" Porter.',
    'Grizzly Peak "Grizzly Pink" Ale.',
    'Kona "Castaway" IPA.',
    'Kona "Pipeline Porter".',
    'Lakefront "PILs" Pilsner.',
    'Lakefront "Riverwest Stein" Amber Lager.',
    'Live Oak "Pilz" Pilsner.',
    'Live Oak "Big Bark" Amber Lager.',
    'Long Trail "Cranberry GOSE".',
    'Long Trail "Green Blaze" IPA.',
    'Magic Hat "#9" Pale Ale.',
    'Magic Hat "Low Key" Session IPA.',
    'Mountain State "Cold Trail" Blonde Ale.',
    'Mountain State "Homegrown" Wet Hop IPA.',
    'New Belgium "1554" Black Lager.',
    'New Belgium "Fat Tire" Belgian Ale.',
    'Oskar Blues "Dale\'s Pale Ale".',
    'Oskar Blues "Old Chub" Scotch Ale.',
    'Pyramid "Outburst" Citrus IPA.',
    'Pyramid "Thunderhead" IPA.',
    'River Horse "Hippotizing" IPA.',
    'River Horse "Tripel Horse" Ale.',
    'Sierra Nevada "Tropical Torpedo" Tropical IPA.',
    'Sierra Nevada "Nooner" Pilsner.',
    'Snake River "Work Day" IPA.',
    'Snake River "Front Yard" Ale.',
    'Southern Star "Bombshell Blonde" Ale.',
    'Southern Star "Conspiracy Theory" IPA.',
    'Wicked Weed "Imperial Coolcumber" Golden Ale.',
    'Wicked Weed "Lunatic Blonde" Belgian Ale.',
    'Wind River "Buckin\' ESB" British Ale.',
    'Wind River "Oatmeal Stout".',
    'Wolf Hills "Carry on Wheatward Son".',
    'Wolf Hills "Creeper Trail" Amber Ale.',
    'Yazoo "Sly Rye" Porter.',
    'Yazoo "Hop Perfect" IPA.'
    ]

var bartsQuotes = [
    'I will not waste chalk.',
    'I will not instigate revolution.',
    'Garlic gum is not funny.',
    'They are laughing at me, not with me.',
    'Tar is not a plaything.',
    'I will not trade pants with others.',
    'I will not sell school property.',
    'I will not sell land in Florida.',
    'I will not grease the monkey bars.',
    'Nobody likes sun burn slappers.',
    'Underwear should be worn on the inside.',
    'I will not conduct my own fire drills.',
    'Funny noises are not funny.',
    'I will not spank others.',
    'I will not spin the turtle.',
    'I will not defame New Orleans.',
    'I will not prescribe medication.',
    'I will not eat things for money.',
    'No one is interested in my underpants.',
    'I will return the seeing-eye dog.',
    'I do not have diplomatic immunity.',
    'I will not send lard through the mail.',
    'I will not scream for ice cream.',
    'I am not a licensed hairstylist.',
    'The capital of Montana is not "Hannah".',
    'I will not laminate dog doo.',
    'The Giving Tree is not a chump.',
    'I will not hide the teacher\'s medication.',
    'I will only provide a urine sample when asked.',
    'I did not see Elvis.',
    'I will not encourage others to fly.',
    'It\'s potato, not potatoe.',
    'I will not do that thing with my tounge.',
    'I will not pledge allegiance to Bart.',
    'I will not hide behind the Fifth Ammendment.',
    'I will finnish what I sta.',
    'I will not fake rabies.',
    'I will not torment the emotionally frail.',
    'I will not barf unless I\'m sick.',
    'My name is not "Dr. Death".',
    'A burp is not an answer.',
    'Coffee is not for kids.',
    'Mud is not one of the four food groups.',
    'I will not sell miracle cures.',
    'I will not charge admission to the bathroom.',
    'Cursive writing does not mean what I think it does.',
    'No one wants to hear from my armpits.',
    'There was no Roman god named "Farticus".',
    'My butt does not deserve a website.',
    'I have neither been there or done that.'
    ]
